connector_image: airbyte/source-wordpress:dev
acceptance_tests:
  spec:
    tests:
      - spec_path: "source_wordpress/spec.yaml"
  connection:
    tests:
      - config_path: "secrets/config.json"
        status: "succeed"
      - config_path: "integration_tests/invalid_config.json"
        status: "failed"
  discovery:
    tests:
      - config_path: "secrets/config.json"
  basic_read:
    tests:
      - config_path: "secrets/config.json"
        configured_catalog_path: "integration_tests/configured_catalog.json"
        empty_streams: []
# TODO uncomment this block to specify that the tests should assert the connector outputs the records provided in the input file a file
#        expect_records:
#          path: "integration_tests/expected_records.jsonl"
#          exact_order: no
  full_refresh:
    bypass_reason: "This connector does not implement incremental sync"
  incremental: 
   tests:
     - config_path: "secrets/config.json"
       configured_catalog_path: "integration_tests/incremental_catalog.json"
       future_state:
          future_state_path: "integration_tests/abnormal_state.json"
       timeout_seconds: 4800
       # When running multiple syncs in a row, we may get the same record set because of a lookback window.
       # This may fail the test but this is expected behavior of the connector.
       skip_comprehensive_incremental_tests: true
