services:
  db:
    image: mysql:8.0
    container_name: db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: your_root_password
      MYSQL_DATABASE: wordpress
      MYSQL_USER: your_wordpress_database_user
      MYSQL_PASSWORD: your_wordpress_database_password
    volumes:
      - dbdata:/var/lib/mysql
      - ./wordpress_dump.sql:/docker-entrypoint-initdb.d/wordpress_dump.sql
    networks:
      - app-network

  wordpress:
    depends_on:
      - db
    image: wordpress:6.7.1-apache
    container_name: wordpress
    restart: unless-stopped
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: your_wordpress_database_user
      WORDPRESS_DB_PASSWORD: your_wordpress_database_password
      WORDPRESS_DB_NAME: wordpress
    volumes:
      - wordpress:/var/www/html
    ports:
      - "8080:80"
    networks:
      - app-network

volumes:
  wordpress:
  dbdata:

networks:
  app-network:
    driver: bridge
