log_level: debug
http_server_host: ":8080"
kafka_group_id: "manager"
broker_host: "localhost:29092"
metastore_host: "localhost"
metastore_port: 9083
spark_host: "localhost"
spark_port: 10000
redis_uri: "redis://localhost:6379/0"
dataspace_host: "http://dataspace-backend.services:3000/pub"
dataservice_host: "http://data-service.data-tooling:9099"
airbyte_config:
  host: "http://localhost:8001/api"
  organization_id: "00000000-0000-0000-0000-000000000000"
  sync_webhook: "http://host.docker.internal:8080/ingestions/airbyte_internal/sync_webhook"
  destination_templates:
    s3:
      definition_id: "4816b78f-1489-44c1-9060-4b19d5fa9362"
      docker_image_tag: "1.3.0"
      bucket_key: "s3_bucket_name"
      config:
        s3_bucket_path: "databases"
        s3_bucket_region: "us-east-1"
        s3_path_format: "${NAMESPACE}/${STREAM_NAME}/ingestion_date=${YEAR}_${MONTH}_${DAY}/"
        file_name_pattern: "{timestamp}.parquet.gzip"
        format:
          format_type: "Parquet"
          compression_codec: "GZIP"
