name: CI

on: 
  push:

jobs:
  changed_files:
    runs-on: ubuntu-latest
    name: Test changed-files
    steps:
      - name: Setup Git
        uses: actions/checkout@v4
      - name: Get list of changed files
        id: changes
        run: |
          # Captura os arquivos modificados
          git diff --name-only ${{ github.event.before }} ${{ github.sha }} > changed_files.txt
          # Extraindo apenas o nome entre as barras (diretório base)
          dir=$(awk -F'/' '{print $2}' changed_files.txt | sort | uniq)
          echo "dir=$dir" >> "$GITHUB_ENV"
      - name: Show changed directories or files
        run: |
          echo "Arquivos ou diretórios alterados:"
          echo "${{ env.dir }}"
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
            role-to-assume: arn:aws:iam::882490700787:role/connectors-source-sage-ghactionsopenid
            aws-region: us-east-1
