name: CI

on: 
  push:
    paths:
      - connectors/**

jobs:
  changed_files:
    runs-on: ubuntu-latest
    name: Test changed-files
    steps:
      - name: Setup Git
        uses: actions/checkout@v4
        with:
          fetch-depth: 2
      - name: Get list of changed files
        id: changes
        run: |
          # Captura os arquivos modificados
          git diff --name-only ${{ github.event.before }} ${{ github.sha }} > changed_files.txt
          # Extraindo apenas o nome entre as barras (diretório base)
          dir=$(awk -F'/' '{print $2}' changed_files.txt | sort | uniq)
          echo "dir=$dir" >> "$GITHUB_ENV"
      - name: Show changed directories or files
        run: |
          echo "Arquivos ou diretórios alterados:"
          echo "${{ env.dir }}"
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'
      - name: Install poetry
        run: pipx install poetry pytest
      - name: Poetry Install Dependencies
        run: poetry install
        working-directory: ./connectors/${{ env.dir }}
      - name: Run Poetry Tests
        run: poetry run pytest --html=report-unit-test.html unit_tests 
        working-directory: ./connectors/${{ env.dir }}
      - name: Upload Test Result
        uses: actions/upload-artifact@v3
        with:
          name: report-unit-test.html
          path: ./connectors/${{ env.dir }}