name: Go - Unit Test and Integrations Test
on:
  push:
  # pull_request:
  #   paths:
  #     - ./connectors/**
jobs:
  E2E_Tests:
    runs-on: ubuntu-latest
    name: End to End Teste
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Git Clone
        uses: actions/checkout@v4
        with:
          submodules: recursive
          ssh-key: '${{ secrets.SSH_PRIVATE_KEY }}'

      - name: Get list of changed files
        id: changes
        run: |
          git diff --name-only ${{ github.event.before }} ${{ github.sha }} -- ./connectors/ > changed_files.txt
          dir=$(awk -F'/' '{print $2}' changed_files.txt | sort | uniq)
          echo "dir=$dir" >> "$GITHUB_ENV"

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'
        
      - name: Install poetry
        run: pipx install poetry pytest
  
      - name: Poetry Install Dependencies
        run: poetry install
        working-directory: ./connectors/${{ env.dir }}

      - name: Run docker-compose
        uses: hoverkraft-tech/compose-action@v2.0.1
        with:
          compose-file: ./connectors/${{ env.dir }}/docker-compose.yaml

      - name: Check Containers
        id: check
        run: docker ps

      - name: End to End Test
        run: go test ./... -tags e2e
        working-directory: ./connectors/${{ env.dir }}

      - name: Shutdown Containers
        id: shutdown
        run: docker-compose down
        working-directory: ./connectors/${{ env.dir }}
