name: Conditional Deploy

on: push

jobs:
  identify-changed-paths:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Get list of changed files
        id: changed-files
        run: |
          # Lista os arquivos alterados para o evento atual
          git diff --name-only ${{ github.event.before }} ${{ github.sha }} > changed_files.txt
          # Adiciona a lista como saída do job
          echo "changed_files=$(cat changed_files.txt | tr '\n' ',')" >> $GITHUB_ENV

      - name: Show changed paths
        run: |
          echo "Arquivos alterados:"
          echo "${{ env.changed_files }}"

      - name: Exemplo de uso do path
        run: |
          for file in $(echo ${{ env.changed_files }} | tr ',' '\n'); do
            echo "Processando arquivo: $file"
          done