name: Go

on:
  push:
    branches: [ "main" ]

jobs:
  Unit_Test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.23'

    - name: Build
      run: go build -v ./...
      working-directory: ./manager

    - name: Unit Test
      run: go test ./...
      working-directory: ./manager

  E2E_Tests:
    runs-on: ubuntu-latest
    name: End to End Teste
    needs: ["Unit_Test"]
    permissions:
        id-token: write
        contents: read
    steps:
      - name: Git Clone
        uses: actions/checkout@v4
      
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.23'
          check-latest: true
          cache-dependency-path: "**/*.sum"
  
      - name: Build
        run: go build -v ./...
        working-directory: ./manager
      
      - name: Run docker-compose
        uses: hoverkraft-tech/compose-action@v2.0.1
        with:
          compose-file: "./manager/docker-compose.yaml"
      
      - name: Check Containers
        id: check
        run: docker ps
        
      - name: End to End Test
        run: go test ./test/e2e/
        working-directory: ./manager

      - name: Shutdown Containers
        id: shutdown  
        run: docker-compose down
        working-directory: ./manager
        