name: Go

on:
  push:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.23'

    - name: Build
      run: go build -v ./...
      working-directory: ./manager

    - name: Unit Test
      run: go test -v ./...
      working-directory: ./manager
    
    - name: End to End Test
      run: go test ./test/e2e/
      working-directory: ./manager
